### ISSUE TITLE
improperly released (or tagged) v0.1.0

### ISSUE THREAD

**Issue by rlyons** [Venafi/vcert-java#7]
Someone within the organization that I am employed by has requested that this item be uploaded into our binary repository.  Unfortunately as it seems to be a snapshot this will automatically be cleaned out after a week...

I think that the tag needs to be changed to v0.1.0-RC1.  If it was meant to be a release, the pom.xml version should reflect that version at the same commit of tagging.

I could clone and run a maven release plugin to properly perform the steps and upload to our internal repository, but I also do not want to be out of step with the official binaries built as intended by your team.

Please let me know which direction we should go forward with.

Thanks,

Roy Lyons

**Comment by tr1ck3r** [comment]
Thank you @rlyons we have been aware of this oversight and are planning to address it in our next release which is currently in code review (https://github.com/Venafi/vcert-java/pull/6).  There will always be a small difference between the naming of the asset because it is our standard practice to also include the build number (e.g. for `v0.1.2` release the asset might be `vcert-java_v0.1.2+95.jar`).

**Comment by tr1ck3r** [comment]
This issue has been resolved with the v0.1.3 release.
